# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-07 21:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contestms', '0005_question_hint'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradeinfo',
            name='is_fb',
            field=models.BooleanField(default=False),
        ),
    ]
